### ISSUE TITLE
[인프라] 캠퍼스 밖에서 서버의 로그를 확인할 수 없다.

### ISSUE THREAD

**Issue by poi1649** [woowacourse-teams/2023-yigongil#190]
## 💡 이쓔

현재 서버가 배포된 ec2안에 로그를 남기고 있는데, 이는 캠퍼스 밖에서 확인할 수 없습니다.
이로 인해 로컬에서는 일어나지 않고, 배포 서버에서만 일어나는 문제의 원인을 파악하기 힘듭니다.

## 📝 투두
- [ ] 파일로 쓰여지는 알림을 로컬에서도 볼 수 있도록 인프라를 구축한다.

## ⏲이슈 시작 예정일 및 추정 소요 시간
- 시작 예정일 : 2023-08-04
- 추정 소요 시간: 5h

**Comment by kevstevie** [comment]
어떤 방식으로 구현되는지 설명해주세요!!
