### ISSUE TITLE
[버그 리포트] 제목, 스터디 소개가 공백이어도 스터디가 개설되는 버그

### ISSUE THREAD

**Issue by Cyma-s** [woowacourse-teams/2023-yigongil#214]
# 어떤 버그인가요?

- 제목, 스터디 소개가 공백 문자열이어도 스터디가 개설됩니다

## 예상 결과

- 공백 문자열인 경우에는 스터디 개설을 막아야 할 것 같아요

## 실제 결과

- 스터디가 잘 개설됩니다

## 스크린샷
![image](https://github.com/woowacourse-teams/2023-yigongil/assets/61370551/70a56c89-40dc-4afc-8f97-72c63221f4bd)

# 버그를 재현하는 방법

제목, 스터디 소개 모두 공백
1. 제목 공백 입력
2. 스터디 공백 입력
3. 스터디 개설

# 어떤 환경에서 발생했나요?

- 기기 및 OS: galaxy s21+ android

**Comment by kevstevie** [comment]
감사합니다

**Comment by inseonyun** [comment]
이걸 찾아주셨네요 일부러 남겨둔 이스터에근데 축하드립니다 누가 잡아주나 기다렸습니다

**Comment by Cyma-s** [comment]
이거 영광이네요
