### ISSUE TITLE
[스터디 개설 뷰] 스터디 개설 기능

### ISSUE THREAD

**Issue by CFalws** [woowacourse-teams/2023-yigongil#25]
## 💡 이쓔
스터디 개설 기능을 추가한다.

## 📝 투두
- [ ] 스터디 정보 검증
- [ ] 라운드 생성

## ⏲이슈 시작 예정일 및 추정 소요 시간
- 시작 예정일 : 2023-07-17
- 추정 소요 시간: 1h 30m

## 🎸 기타

ex) 민트 칭찬해 ~

**Comment by yujamint** [comment]
Good!
