### ISSUE TITLE
Study 엔티티를 수정한다

### ISSUE THREAD

**Issue by yujamint** [woowacourse-teams/2023-yigongil#452]
## 💡 이쓔

1. 스터디 개설에 포함되는 정보를 수정한다.
2. 스터디 시작 API 구현
3. 스터디 종료 API 구현
스터디 개설, 목록, 조회, 시작

### 목록
- 평균 티어
- 개설일
- 제목
- 인원
- 상태(모집중, 종료, 진행중)

전체 / 모집중 / 수락 대기중으로 필터링
- 수락 대기중 API 분리해야 하는가? 분리로 결론
- 전체와 모집중은 쿼리 파람 사용

### 조회(스상조)
빼야 하는 정보
- 예상시작일
- 스터디 주기
- 현재 회차
- 전체 회차

추가되는 정보
- 주 몇 회(스터디 주기를 대체)
- 최소 몇 주? (스터디 기간)

### 개설
첫 번째 뷰
- 제목
- 내용

두 번째 뷰
- 인원수
- 최소 몇 주
- 주 몇 회

기존 뷰에서의 제거 사항
- 예상시작일
- 스터디 기간
- 스터디 주기

뷰는 여러개로 나뉘지만, 한 API로 요청

### 시작
입력받는 정보
- 요일
  - 유저가 입력한 요일만큼 스터디 정보(주 몇 회) 수정

### 종료
- 최소 기간 지나면 종료 가능

회차 정보 조회
- 현재 회차 인증정보
- 현재 주차
- 현재 요일

주차 조회 -> 반환받은 현재 주차 사용
- 주차의 정보 조회 (요일별 todo content)

### study
빠지는 정보
- 스터디 주기

수정되는 정보
- startAt -> 예상시작일의 의미는 없고, 시작일의 의미만 가진다.

추가되는 정보
- 스터디가 진행되는 요일들
- 최소 기간

### 회차
- 요일
- 주차

매핑테이블 두개

## 작업 할당
- 엔티티 구현 (에밀) **~9/27 00:00**
- 스터디 상세 조회 (에밀 / 128)
- 스터디 종료 (주드 / 129)
- 스터디 목록 조회 (주드 / 132)
- 스터디 개설 (민트 / 126)
- 스터디 시작 (포이 / 140)
~10/04 00:00까지

## 현재 존재하는 스터디는?
상의 결과를 [노션](https://www.notion.so/121286633ff64fdebc97b48e34dac99b?pvs=4)에 기록함.

**Comment by poi1649** [comment]
### 1차 논의된 내용
- 상속을 가져가는가? 
    - 가져가는 게 지금까지 나온 논의사항 중 제일 변경이 적을 것 같다.
- 상속을 가져간다면 라운드를 분리해도 좋을 것 같다.
- 엔티티를 하나로 가져가면 시간이 지날수록 계속해서 필드가 늘어날 가능성이 있다. 
- 서비스도 두개로 나누자
    - 공통로직은 파사드 패턴으로 적용 가능
- 인스턴스 자체를 분리한다. (새로운 서버를 새로운 인스턴스에 띄운다, 교살자 패턴 적용)
- 서비스를 인터페이스화 한다.

### 안드로이드 클라이언트가 새로운 버전으로 업데이트가 안되어있을 경우
- 목록 조회에 띄워주면 업데이트를 유도할 수 있다.(클라이언트단에서 처리가 가능 할 경우)

### 선택지 정리
- 엔티티 상속
    - 공통 레파지터리 사용해서 구현체 가져올 수 있으면 중복코드 최소화 가능
- 서버 분리
- ~엔티티 널칼럼~
- 서비스 분리
    - 구현 서비스 인터페이스 두고 실제 서비스는 인터페이스의 구현에 로직 의존함(중복 코드 제거 가능)
- 서비스가 응답으로 레스폰스를 줘도 되는지
    - 도메인을 주는 편이 좋다. (다른 서비스에서도 파사드로 재사용을 계속 가능)

**Comment by poi1649** [comment]
## 2차 논의된 내용

### 구버전에서 신버전 엔티티를 보여줄 것인가

1. 업데이트를 강제한다.
    - 업데이트의 규모가 상당히 크다. 이정도의 규모라면 강제 업데이트가 적절해 보인다.

업데이트 강제했을 때도 여전히 해결해야 하는 문제점은?

- v2에서 v1을 조회할 때 어떻게 할까?
    1. v1 스터디와 v2 스터디를 나눠서 보여준다.
    2. v1 스터디와 v2 스터디를 함께 보여준다.
        - v1 스터디는 v2에 맞게 마이그레이션 하는 과정이 필요

### v2 버전에서 v1의 스터디 상세 보기를 어떻게 처리할 것인가

- v1 버전의 스터디는 v2에 맞게 새로운 정보를 입력하도록 사용자에게 요청한다.
    - **스터디장에게 추가 정보를 기입받기 전까지는 스터디 정보를 공백으로 보여준다.**
- 이미 종료된 스터디는 v1과 v2가 공통적으로 가지고 있는 데이터만 표기한다.

### 날릴까 말까

**날린다**

v2의 기획에선 다음 주차의 투두까지만 설정할 수 있음.

너무 큰 규모의 업데이트고, 해야 할 업무가 너무 많은 현재로써는 기존의 데이터를 모두 날리고 강제 업데이트를 하는 것이 현실적인 방안인 것 같다. 현재는 사용자도 없는 상태.

**만다**

v1의 스터디를 무사히 마칠 수 있도록 v1과 v2를 동시에 운영한다. 대신 생성 기능은 막아 놓는다.

**현재 클라이언트에 버저닝 관련 코드 미적용 됨 + 시간적 제약으로 위해 이번 버전에서는 하위호환성을 고려하지 않기로 결정**

### 개선안

**안드로이드**

- 버전관리 코드 넣기(알림 시스템) 
    - 메시지가 기획에 따라 변경될 수 있으므로 웹뷰 또는 서버 단에서 메시지를 가져올 수 있도록 설계

<aside>
💡 빠지는 정보 + 추가되는 정보

</aside>

빼야 하는 정보

- 예상시작일
- 스터디 주기
- 현재 회차
- 전체 회차

추가되는 정보

- 주 몇 회(스터디 주기를 대체)
- 최소 몇 주? (스터디 기간)
- 요일
