### ISSUE TITLE
[스레드 뷰] MustDo UI수정

### ISSUE THREAD

**Issue by s9hn** [woowacourse-teams/2023-yigongil#567]
## 📝 투두

- [ ] 
- [ ]

## ⏲이슈 시작 예정일 및 추정 소요 시간
- 시작 예정일 : 2023-02-07
- 추정 소요 시간: 3d

## 🎸 기타

ex) 민트 칭찬해 ~

**Comment by no1msh** [comment]
![image](https://github.com/woowacourse-teams/2023-yigongil/assets/22425650/658f1de3-2a2d-4d0d-bb71-7192e6bca784)
![image](https://github.com/woowacourse-teams/2023-yigongil/assets/22425650/d7bebe14-6492-4ba9-9bc0-65d7592a4837)
![image](https://github.com/woowacourse-teams/2023-yigongil/assets/22425650/ff32bf2d-db01-4074-8afd-d888d030554c)
