### ISSUE TITLE
[백엔드 버그 수정] 네임드 파라미터를 통한 쿼리가 특정 jdk 버전에서 제대로 동작하지 않는 현상 수정

### ISSUE THREAD

**Issue by poi1649** [woowacourse-teams/2023-yigongil#61]
## 💡 이쓔
네임드 파라미터를 통한 쿼리가 특정 jdk 버전에서 제대로 동작하지 않는 현상이 나타난다.

## 📝 투두
- [ ] 네임드 파라미터를 통해 쿼리시, 파라미터의 이름을 명시한다.

## ⏲이슈 시작 예정일 및 추정 소요 시간
- 시작 예정일 : 2023-07-19
- 추정 소요 시간: 10m

## 🎸 기타
ex) 민트 칭찬해 ~

**Comment by kevstevie** [comment]
jdk 같은 버전 쓰지 않나요
