### ISSUE TITLE
서버의 로컬/테스트/프로덕션 환경을 분리한다

### ISSUE THREAD

**Issue by yujamint** [woowacourse-teams/2023-yigongil#98]
## 💡 이쓔
로컬/테스트/프로덕션 환경에서의 환경 변수를 분리한다.

## 📝 투두

- [ ] 테스트 환경을 설정한다.
  - [ ] H2 DB (In-Memory)
- [ ] 로컬 환경을 설정한다.
  - [ ] H2 DB
- [ ] 프로덕션 환경을 설정한다.
  - [ ] Maria DB
  - [ ] 에러 로깅

## ⏲이슈 시작 예정일 및 추정 소요 시간
- 시작 예정일 : 2023-07-23
- 추정 소요 시간: 2h

## 🎸 기타

ex) 민트 칭찬해 ~

**Comment by kevstevie** [comment]
이거 근데 내일 같이 적용해야하는거 아닌가요
ec2도 띄워야해서

**Comment by yujamint** [comment]
같이 해야 될 거 같은 부분 제외하고 어느정도 틀만 해놨어요
낼 같이 보면서 수정할 부분 수정하고 같이 할 부분 해보져
